Newbranch
enocol/HelloMicroverse pull request #1
Opened 2023-05-30 12:51 UTC by enocol

2023-05-30 13:24 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @enocol👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
- Good commit messages ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 13:24 UTC, AbelG101 commented on .gitignore
**THIS COMMENT IS REGARDING YOUR BRANCH NAME AND PULL REQUEST**
- [ ] Ouch! this is so close but kindly make sure your branch is the name of a feature or action (e.g. 'created_hello_microverse_file' or 'added_hello_microverse').
- [ ] When you rename your branch it will close the current pull request so please create a new PR and add a link to this PR. So that the 2nd reviewer can check it for you. 😉
- [ ] Kindly make sure you have a proper PR title that describes what the changes are about.
    ![image](https://github.com/enocol/HelloMicroverse/assets/104968236/dfbac5c0-beb2-4f46-af27-824a75113882)
- [ ] Also please make sure you provide a proper PR description as this gives a quick overview of the changes you've implemented. ✔

2023-05-30 13:24 UTC, AbelG101 commented on A.css
- [ ] Kindly make sure to use the proper readme template provided by microverse, which [you can find here](https://github.com/microverseinc/readme-template/blob/master/README.md). As this ensures your project is well documented and follows best practices. ✔
     - [ ] Now once you've added the proper template make sure to remove any section descriptions from it, like the one below 👇
       ![image](https://github.com/enocol/HelloMicroverse/assets/104968236/4cd4cb72-e43a-4503-b24f-e1526b569069)
- [ ] Also please make sure to add a proper license link, like an MIT link which you can find here, and also update the License section of your readme so it links to the MIT file you've added.

2023-05-30 15:52 UTC, enocol commented on A.css
I am trying to get use to the jargons used here as this is my second day. I included a Readme file in this project but I understand that it does not contain much, I thought the exercise was just to understand to include a ReadMe file. Also, in order to use the proposed ReadMe template, I have not yet figured out how to use this template because I believe the template is just a template but the content of the ReadMe file is what is essential. I have not seen any proper instructions on how to use the said template.

2023-05-30 16:00 UTC, enocol commented on A.css
Also, I just wish to find out if using a proper ReadMe template is mandatory.

2023-05-30 17:48 UTC, enocol commented on A.css
@AbelG101 thanks for your review. I thought the exercise was just to understand how what tools are needed to be available when working on a project. Also was it mandatory to use the said READMe file template? I thought the lesson was to understand the need and necessity of a ReadMe file and what it uses for. I included a Readme file with just a line of text.

2023-05-30 20:01 UTC, enocol commented on .gitignore
Branch name now changed

2023-05-30 20:02 UTC, enocol commented on A.css
ReadMe file template used. Most of the content was deleted

2023-05-30 20:02 UTC, enocol commented on A.html
eslint only added for now.

2023-05-30 20:40 UTC, V-Blaze requested changes
## Hi @enocol , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Correct Gihub Flow✔

 ## Required Changes ♻️
- [ ] Currently, your pull request does not have a summary description, As part of the requirement for every pull request, you need to add a summary, The summary is a brief point that let you tell others about changes you've pushed to a branch in a repository on GitHub. I'll suggest you click on the 3 dots at the top `see screenshot bellow` and add a proper description for this pull request. :+1: :smile: 

- - ![Selection_050](https://github.com/enocol/HelloMicroverse/assets/107632780/2f905c87-37b9-4636-90e1-721969dc9fc2)

> Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.

- [ ] I can see you tried setting up linters for your project, but I think the setup is not complete and therefore the linters are not running. The structure of the linters folder is. You create a `.github folder` then you create a `workflows folder` inside it, then you create a `linters.yml file` inside it. Try to keep in mind the difference between folders and files here and also the capitalization of the file's name. Here is the [link to the linters setup repository,](https://github.com/microverseinc/linters-config) Follow the direction and set up the linters correctly for your project. :wave: :+1: 

- - If your linters setup is correct, you are going to see the linters running on your pull request, and you are going to see something link this on your pull request:

- - Screenshot: 
![Screenshot from 2023-05-30 15-35-09](https://github.com/hamidazim321/Hello-Microverse/assets/107632780/0d73ba3c-77d2-402d-b242-e0abd58d771d)



## Optional suggestions
- [OPTIONAL] Your commit messages are good but following the best practices, you are meant to capitalize the first letter of the first word in the message, I'll suggest you put this into practice in your subsequent projects :+1: :+1: 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 20:40 UTC, V-Blaze commented on README.md
> +
> Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

- [ ] You did great using the provided Microverse readme template. :+1: :+1: Looking at the readme file, it seems you have removed most of the important sections and also not customized it to your project. As the previous reviewer suggested and also According to Microverse the only optional section is the FAQ, you are meant to customize every other section in your readme file. :smile: :wave: I'll suggest you get the [template once more,](https://github.com/microverseinc/readme-template) make sure you do not remove any section. Then go through your readme and remove the placeholder logo and texts, and then fill the content of every section in the readme file :+1: :100: 

## To answer your comment [here](https://github.com/enocol/HelloMicroverse/pull/1/files#r1210619588), the code is being reviewed based on the tasks you were asked to perform in the project requirement, You are meant to use the provided readme template and also you are meant to customize it to match your project.

- - Project requirement screenshot:
![Screenshot from 2023-05-30 21-25-05](https://github.com/enocol/HelloMicroverse/assets/107632780/afc5ca5e-2018-4f16-8157-76583c279051)

2023-05-30 20:40 UTC, V-Blaze commented on MIT.md
> +THE [APP TYPE] IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEM
- [ ] You did great adding the MIT license as suggested by the previous reviewer, :+1: But just as the readme file, you are also meant to customize this file, I'll suggest you go file and update the `YOUR NAME` and `APP TYPE` place holder to your name and the name of this your project. :+1: :smile:

2023-05-30 23:09 UTC, enocol commented on README.md
> +
By deleting the other sections of the template ReadMe file, I was customizing the template to my project. The ReadMe file is very lengthy and most of, if not all of its content are irrelevant to my project. That's why I deleted all of its content. I have now updated the readme file and removed the logo section, added some description of the project and the rest of the content is there. I think my takeaway here is that I have learned how to include a read-me file and learned about its use and importance. The content of that file at this stage should not be a big deal. As we go along with more sophisticated projects, I believe I will have a more meaningful readme file with useful content.

2023-05-31 06:59 UTC, enocol commented on MIT.md
> +THE [APP TYPE] IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEM
I have included my name and web type. Hope that's ok for now.

2023-05-31 07:35 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @enocol    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ Used correct GitFlow👍 
✔ No Linter Errors 👍 
✔ Professional PR👍 

## Required Changes ♻️

- [x]  Check the comments below 


## Optional requirements ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 07:35 UTC, TuyishimireEric commented on README.md
> +
- [ ] **[OPTIONAL]**, I think it would be better to remove all placeholder texts that describe what should be done in each section 😎eg: `Describe the tech stack and include only the relevant sections that apply to your project.` this message is here to guide the other 👍 please remove all messages like this to make you README more professional 👍

2023-05-31 07:35 UTC, TuyishimireEric commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Kindly **As suggested by the previous reviewer,** I think it would be better to provide a valid link to the license file to make your Readme user-friendly 🙏

eg: 
```
This project is [MIT](./MIT.md) licensed.

2023-05-31 07:50 UTC, enocol commented on README.md
> +
This project is a one-line html doc styled with less than 5 lines of CSS. I have previously customized the ReadMe with just a project description and nothing else. Your colleague requested that I get the full template etc. Now you are asking me to remove sections that are not relevant. In this Readme file template, little or nothing is relevant to this project. The author's name and project description was all it needed if you ask me.

2023-05-31 08:09 UTC, enocol commented on README.md
> +This project is [MIT](./LICENSE) licensed.
![image](https://github.com/enocol/HelloMicroverse/assets/129378066/969e1e90-6f84-44ff-a6ec-69d3286b6dcf)

2023-05-31 08:09 UTC, enocol commented on README.md
> +This project is [MIT](./LICENSE) licensed.
please let me know because this was here before.

2023-05-31 08:11 UTC, enocol commented on README.md
> +This project is [MIT](./LICENSE) licensed.
@TuyishimireEric  please let me because this license link was here before.

2023-05-31 09:16 UTC, V-Blaze approved these changes
Hi @enocol  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Readme looks professional 💯
- Linters setup correctly 👍 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 09:36 UTC, merged

2023-05-31 09:40 UTC, enocol commented
Thank you Valentine for actually calling me and showing me how to deal with the ReadMe file including other aspects of the project. Big Thumps up!